#第三章
#添加配置文件application.yml(相比.properties配置更有层次感)
#配置DataSource及JPA
#spring:
#  datasource:      #配置mysql数据源
#    url: jdbc:mysql://127.0.0.1:3306/bootdb?characterEncoding=utf8
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: shiyufeng
#jpa:
#  database: MySQL
#  show-sql: true   #用来在控制台输出JPA自动生成的sql语句
#  hibernate:
#    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

#第四章 SpringBoot整合Druid连接池
spring:
  datasource: #配置mysql数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bootdb?characterEncoding=utf8
    username: root
    password: shiyufeng
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，wall用于防火墙
    filters: stat,wall,log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能，慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true

#第五章
mvc:
  view:
    prefix: /WEB-INF/jsp/
    suffix: jsp